name: Deploy to heroku test 1

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Deploy to Heroku
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        env:
          HEROKU_API_TOKEN: ${{ secrets.HEROKU_API_TOKEN }}
          HEROKU_APP_NAME: "testactions"      
        run:
          git push https://heroku:$HEROKU_API_TOKEN@git.heroku.com/testactions.git origin/master:master
