name: Deploy to heroku test 1

on:
  push:
    branches:
      - master

# via https://github.com/AmericanAirlines/Hangar/commit/94ba0b8920659a623975377d71275285a65a2a83#diff-da4ee0d9a13a73c0e16c7b55acb219d7
jobs:
  release:
   runs-on: ubuntu-latest
   steps:
    - name: install stuff
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: |
        echo "test"
        npm install
        heroku --version
        echo "hm"
        
    - name: another test
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: |
        echo "test 2"
