name: Deploy to heroku test 1

on:
  push:
    branches:
      - master

# via https://github.com/AmericanAirlines/Hangar/commit/94ba0b8920659a623975377d71275285a65a2a83#diff-da4ee0d9a13a73c0e16c7b55acb219d7
jobs:
  release:
   runs-on: ubuntu-latest
   steps:
    # https://help.github.com/en/actions/automating-your-workflow-with-github-actions/configuring-a-workflow#using-the-checkout-action
    - uses: actions/checkout@v1.0.0
    - name: save heroku credentials to file
      run: | 
          cat >~/.netrc <<EOF
          machine api.heroku.com
              login $HEROKU_EMAIL
              password $HEROKU_LOGIN_API_KEY
          machine git.heroku.com
              login $HEROKU_EMAIL
              password $HEROKU_LOGIN_API_KEY
          EOF
    - name: install stuff
      run: |
        echo "test"
        ls
        npm install
        heroku --version
        cat ~/.netrc
        git status
        heroku git:remote -a ${{ secrets.HEROKU_APP_NAME }}
        git push heroku HEAD:master
        
    - name: another test
      run: |
        echo "test 2"
