name: Deploy to heroku test 1

on:
  push:
    branches:
      - master

# via https://github.com/AmericanAirlines/Hangar/commit/94ba0b8920659a623975377d71275285a65a2a83#diff-da4ee0d9a13a73c0e16c7b55acb219d7
jobs:
  release:
   runs-on: ubuntu-latest
   steps:
    - name: save heroku credentials to file
      run: | 
          cat >~/.netrc <<EOF
          machine api.heroku.com
              login $HEROKU_EMAIL
              password $HEROKU_API_KEY
          machine git.heroku.com
              login $HEROKU_EMAIL
              password $HEROKU_API_KEY
          EOF
    - name: install stuff
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: |
        echo "test"
        ls
        npm install
        heroku --version
        heroku git:remote -a $(basename $GITHUB_REPOSITORY)
        git push heroku master
        
    - name: another test
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: |
        echo "test 2"
