name: Test Sentry CLI

on:
  push:
    branches:
      - master
jobs:
  release:
   runs-on: ubuntu-latest
   env:
     SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
     SENTRY_ORG: liz
     SENTRY_PROJECT: round-robin
   steps: 
    - name: install sentry cli?
      run: |
        which sentry-cli
        sentry-cli --version
        curl -sL https://sentry.io/get-cli/ | bash
        which sentry-cli
        sentry-cli --version
        sentry-cli info
