name: Test Sentry CLI

on:
  push:
    branches:
      - master
jobs:
  release:
   runs-on: ubuntu-latest
   env:
     SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
     SENTRY_ORG: liz
     SENTRY_PROJECT: round-robin
   steps: 
    - name: install sentry cli?
      run: |
#        curl -sL https://sentry.io/get-cli/ | bash
        npm install 
        echo $SENTRY_AUTH_TOKEN
        echo $SENTRY_ORG
        echo $SENTRY_PROJECT
        sentry-cli info
        pwd
        heroku config:set SENTRY_ORG=$SENTRY_ORG
        
