name: Test Sentry CLI

on:
  push:
    branches:
      - master
jobs:
  release:
   runs-on: ubuntu-latest
   env:
     SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
     SENTRY_DSN: https://40d39f91e8e74b5d887ff877a7b14961@sentry.io/1848428
     SENTRY_ORG: liz
     SENTRY_PROJECT: testactions
     HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
     SENTRY_RELEASE: test222
   steps: 
    - name: install sentry cli?
      run: |
        curl -sL https://sentry.io/get-cli/ | bash
        echo $SENTRY_AUTH_TOKEN
        echo $SENTRY_ORG
        echo $SENTRY_PROJECT
        sentry-cli info
        pwd
        sentry-cli releases new -p $SENTRY_PROJECT $SENTRY_RELEASE
        sentry-cli releases finalize $SENTRY_RELEASE
        heroku config:set SENTRY_RELEASE=$SENTRY_RELEASE -a ${{ secrets.HEROKU_APP_NAME }}
